theme: jekyll-theme-minimal
title: EWAF24
description: [Swati Swati . Arjun Roy . Eirini Ntoutsi, <br/>, Cite As]
show_downloads: false
logo: /assets/img/EWAF_Poster.pptx.png
github:
  is_project_page: false
