theme: jekyll-theme-minimal
title: EWAF24
description: [Swati Swati . Arjun Roy . Eirini Ntoutsi <br/> Swati Swati, Arjun Roy, and Eirini Ntoutsi “Exploring Fusion Techniques in Multimodal AI-Based Recruitment: Insights from FairCVdb”. In the Proceedings of EWAF’24: European Workshop on Algorithmic Fairness. 2024.]
show_downloads: false
logo: /assets/img/EWAF_Poster.pptx.png
github:
  is_project_page: false
